service: persona-generator

provider:
  name: aws
  runtime: ${file(./config.yml):provider.runtime}
  region: ${file(./config.yml):provider.region}
  stage: ${file(./config.yml):provider.stage}

functions:
  app:
    handler: lambda/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any
plugins:
  - serverless-domain-manager
#   - serverless-vpc-plugin

custom:
  customDomain:
    domainName: ${file(./config.yml):customDomain.domainName}
    certificateArn: ${file(./config.yml):customDomain.certificateArn}
    basePath: v1
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: regional
    securityPolicy: tls_1_2

  # vpc:
  #   cidr: '10.0.0.0/16'
  #   zones:
  #     - ${self:provider.region}a
  #     - ${self:provider.region}b
  #   subnetGroups:
  #     - name: LambdaSubnets
  #       type: private
  #       tags:
  #         - Key: Name
  #           Value: lambda-private-subnet

  # vpc:
  #   cidr: '10.0.0.0/16'
  #   useNatGateway: true

# package:
#   individually: true
#   patterns:
#     - '!node_modules/**'
#     - '!.git/**'
#     - '!.github/**'
#     - '!.vscode/**'
#     - '!test/**'
#     - '!src/**'
#     - '!dist/**'
#     - '!.env*'
#     - '!README.md'
#     - '!CHANGELOG.md'
#     - '!package.json'
#     - '!package-lock.json'
#     - '!pnpm-lock.json'
#     - '!tsconfig.json'
#     - '!.eslintrc.js'
#     - '!.prettierrc'
