export const PLUGIN_NAMES = [
  // Blockchain & Web3
  '@elizaos/plugin-0g',
  '@elizaos/plugin-abstract',
  '@elizaos/plugin-akash',
  '@elizaos/plugin-allora',
  '@elizaos/plugin-anyone',
  '@elizaos/plugin-aptos',
  '@elizaos/plugin-arthera',
  '@elizaos/plugin-asterai',
  '@elizaos/plugin-autonome',
  '@elizaos/plugin-avail',
  '@elizaos/plugin-avalanche',
  '@elizaos/plugin-binance',
  '@elizaos/plugin-coinbase',
  '@elizaos/plugin-coingecko',
  '@elizaos/plugin-coinmarketcap',
  '@elizaos/plugin-conflux',
  '@elizaos/plugin-cosmos',
  '@elizaos/plugin-cronoszkevm',
  '@elizaos/plugin-depin',
  '@elizaos/plugin-evm',
  '@elizaos/plugin-flow',
  '@elizaos/plugin-fuel',
  '@elizaos/plugin-genlayer',
  '@elizaos/plugin-hyperliquid',
  '@elizaos/plugin-icp',
  '@elizaos/plugin-multiversx',
  '@elizaos/plugin-near',
  '@elizaos/plugin-rabbi-trader',
  '@elizaos/plugin-solana',
  '@elizaos/plugin-spheron',
  '@elizaos/plugin-starknet',
  '@elizaos/plugin-sui',
  '@elizaos/plugin-ton',
  '@elizaos/plugin-zksync-era',
  '@elizaos/plugin-solana-agentkit',
  '@elizaos/plugin-movement',

  // Content & Media
  '@elizaos/plugin-3d-generation',
  '@elizaos/plugin-story',
  '@elizaos/plugin-image-generation',
  '@elizaos/plugin-nft-generation',
  '@elizaos/plugin-video-generation',
  '@elizaos/plugin-tts',
  '@elizaos/plugin-gitbook',
  '@elizaos/plugin-obsidian',

  // Development & Platform
  '@elizaos/plugin-bootstrap',
  '@elizaos/plugin-goat',
  '@elizaos/plugin-intiface',
  '@elizaos/plugin-node',
  '@elizaos/plugin-tee',
  '@elizaos/plugin-tee-log',
  '@elizaos/plugin-tee-marlin',
  '@elizaos/plugin-trustdb',
  '@elizaos/plugin-goplus',
  '@elizaos/plugin-opacity',

  // Integration & Services
  '@elizaos/plugin-twitter',
  '@elizaos/plugin-web-search',
  '@elizaos/plugin-whatsapp',
  '@elizaos/plugin-echochambers',
  '@elizaos/plugin-open-weather',
  '@elizaos/plugin-giphy',
] as const;
