#!/bin/bash

envJsonFilename="env.json"
dotenv=".env"
lambdaFunctionName="PersonaGeneratorService"
pkgPersonaGenerator="packages/persona-generator"

echo "🤖 Development local API..."

if ! command -v sam >/dev/null 2>&1; then
  echo "👹 Oops! The aws SAM CLI is required. You must install it. Learn more by visiting https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html"

  exit 1
fi

if [[ ! -f "$dotenv" ]]; then
  echo "👹 Oops! Missing the dotenv file. Check the README, please!"

  exit 1
fi

source "$dotenv"

if [[ -z "$PRIVATE_OPENAI_COMPATIBLE_API_KEY" || -z "$PUBLIC_OPENAI_COMPATIBLE_API_URL" || -z "$PUBLIC_OPENAI_COMPATIBLE_MODEL" ]]; then
  echo "👹 Oops! You seem to have failed to provide the required environment variables? Check the README, please!"

  exit 1
fi

echo "{
  \"$lambdaFunctionName\": {
    \"PRIVATE_OPENAI_COMPATIBLE_API_KEY\": \"$PRIVATE_OPENAI_COMPATIBLE_API_KEY\",
    \"PUBLIC_OPENAI_COMPATIBLE_API_URL\": \"$PUBLIC_OPENAI_COMPATIBLE_API_URL\",
    \"PUBLIC_OPENAI_COMPATIBLE_MODEL\": \"$PUBLIC_OPENAI_COMPATIBLE_MODEL\"
  }
}" > "$envJsonFilename"

(
  echo "🤖 Rebuild $pkgPersonaGenerator..."

  cd "$pkgPersonaGenerator"

  bun run build
)

sam build --build-in-source
sam local start-api --debug --env-vars "$envJsonFilename"
