#!/bin/bash

echo "🕵️ Validate infra template against recommended AWS practices..."

serverlessRules="cfn_lint_serverless.rules"

if ! cfn-lint --rules "$serverlessRules" template.yaml; then
  echo "🚑 Found some issues!"

  exit 1
fi

echo "✅ Seems healthy!"
